name: Release Windows Binary

on:
  push:
    tags:
      - 'v*.*.*'  # Triggers on tags like v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build release
        run: cargo build --release

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: target/release/greeter.exe
          generate_release_notes: true